//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Izibiz.AuthenticationWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_ERRORType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int eRROR_CODEField;
        
        private string eRROR_SHORT_DESField;
        
        private string eRROR_LONG_DESField;
        
        private string sTACKTRACEField;
        
        private int eRROR_ELEMENT_INDEXField;
        
        private bool eRROR_ELEMENT_INDEXFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
                this.RaisePropertyChanged("CLIENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ERROR_CODE {
            get {
                return this.eRROR_CODEField;
            }
            set {
                this.eRROR_CODEField = value;
                this.RaisePropertyChanged("ERROR_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ERROR_SHORT_DES {
            get {
                return this.eRROR_SHORT_DESField;
            }
            set {
                this.eRROR_SHORT_DESField = value;
                this.RaisePropertyChanged("ERROR_SHORT_DES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ERROR_LONG_DES {
            get {
                return this.eRROR_LONG_DESField;
            }
            set {
                this.eRROR_LONG_DESField = value;
                this.RaisePropertyChanged("ERROR_LONG_DES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STACKTRACE {
            get {
                return this.sTACKTRACEField;
            }
            set {
                this.sTACKTRACEField = value;
                this.RaisePropertyChanged("STACKTRACE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int ERROR_ELEMENT_INDEX {
            get {
                return this.eRROR_ELEMENT_INDEXField;
            }
            set {
                this.eRROR_ELEMENT_INDEXField = value;
                this.RaisePropertyChanged("ERROR_ELEMENT_INDEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERROR_ELEMENT_INDEXSpecified {
            get {
                return this.eRROR_ELEMENT_INDEXFieldSpecified;
            }
            set {
                this.eRROR_ELEMENT_INDEXFieldSpecified = value;
                this.RaisePropertyChanged("ERROR_ELEMENT_INDEXSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sESSION_IDField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GIBUSER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDENTIFIERField;
        
        private string aLIASField;
        
        private string tITLEField;
        
        private string tYPEField;
        
        private string rEGISTER_TIMEField;
        
        private string uNITField;
        
        private string aLIAS_CREATION_TIMEField;
        
        private string aCCOUNT_TYPEField;
        
        private string dELETEDField;
        
        private string aLIAS_DELETION_TIMEField;
        
        private string dOCUMENT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDENTIFIER {
            get {
                return this.iDENTIFIERField;
            }
            set {
                this.iDENTIFIERField = value;
                this.RaisePropertyChanged("IDENTIFIER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ALIAS {
            get {
                return this.aLIASField;
            }
            set {
                this.aLIASField = value;
                this.RaisePropertyChanged("ALIAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
                this.RaisePropertyChanged("TITLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string REGISTER_TIME {
            get {
                return this.rEGISTER_TIMEField;
            }
            set {
                this.rEGISTER_TIMEField = value;
                this.RaisePropertyChanged("REGISTER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
                this.RaisePropertyChanged("UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ALIAS_CREATION_TIME {
            get {
                return this.aLIAS_CREATION_TIMEField;
            }
            set {
                this.aLIAS_CREATION_TIMEField = value;
                this.RaisePropertyChanged("ALIAS_CREATION_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ACCOUNT_TYPE {
            get {
                return this.aCCOUNT_TYPEField;
            }
            set {
                this.aCCOUNT_TYPEField = value;
                this.RaisePropertyChanged("ACCOUNT_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DELETED {
            get {
                return this.dELETEDField;
            }
            set {
                this.dELETEDField = value;
                this.RaisePropertyChanged("DELETED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ALIAS_DELETION_TIME {
            get {
                return this.aLIAS_DELETION_TIMEField;
            }
            set {
                this.aLIAS_DELETION_TIMEField = value;
                this.RaisePropertyChanged("ALIAS_DELETION_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
                this.RaisePropertyChanged("DOCUMENT_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class ATTRIBUTESTYPE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nAMEField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class CHANGE_INFOType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime cDATEField;
        
        private long cPOSITION_IDField;
        
        private long cUSER_IDField;
        
        private System.DateTime uDATEField;
        
        private bool uDATEFieldSpecified;
        
        private long uPOSITION_IDField;
        
        private bool uPOSITION_IDFieldSpecified;
        
        private long uUSER_IDField;
        
        private bool uUSER_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime CDATE {
            get {
                return this.cDATEField;
            }
            set {
                this.cDATEField = value;
                this.RaisePropertyChanged("CDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long CPOSITION_ID {
            get {
                return this.cPOSITION_IDField;
            }
            set {
                this.cPOSITION_IDField = value;
                this.RaisePropertyChanged("CPOSITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long CUSER_ID {
            get {
                return this.cUSER_IDField;
            }
            set {
                this.cUSER_IDField = value;
                this.RaisePropertyChanged("CUSER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime UDATE {
            get {
                return this.uDATEField;
            }
            set {
                this.uDATEField = value;
                this.RaisePropertyChanged("UDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UDATESpecified {
            get {
                return this.uDATEFieldSpecified;
            }
            set {
                this.uDATEFieldSpecified = value;
                this.RaisePropertyChanged("UDATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long UPOSITION_ID {
            get {
                return this.uPOSITION_IDField;
            }
            set {
                this.uPOSITION_IDField = value;
                this.RaisePropertyChanged("UPOSITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPOSITION_IDSpecified {
            get {
                return this.uPOSITION_IDFieldSpecified;
            }
            set {
                this.uPOSITION_IDFieldSpecified = value;
                this.RaisePropertyChanged("UPOSITION_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long UUSER_ID {
            get {
                return this.uUSER_IDField;
            }
            set {
                this.uUSER_IDField = value;
                this.RaisePropertyChanged("UUSER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UUSER_IDSpecified {
            get {
                return this.uUSER_IDFieldSpecified;
            }
            set {
                this.uUSER_IDFieldSpecified = value;
                this.RaisePropertyChanged("UUSER_IDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_HEADERType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sESSION_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private long iNTL_TXN_IDField;
        
        private bool iNTL_TXN_IDFieldSpecified;
        
        private long iNTL_PARENT_TXN_IDField;
        
        private bool iNTL_PARENT_TXN_IDFieldSpecified;
        
        private System.DateTime aCTION_DATEField;
        
        private bool aCTION_DATEFieldSpecified;
        
        private CHANGE_INFOType cHANGE_INFOField;
        
        private string rEASONField;
        
        private string aPPLICATION_NAMEField;
        
        private string hOSTNAMEField;
        
        private string cHANNEL_NAMEField;
        
        private string sIMULATION_FLAGField;
        
        private string cOMPRESSEDField;
        
        private ATTRIBUTESTYPE[] aTTRIBUTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
                this.RaisePropertyChanged("CLIENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_TXN_IDSpecified {
            get {
                return this.iNTL_TXN_IDFieldSpecified;
            }
            set {
                this.iNTL_TXN_IDFieldSpecified = value;
                this.RaisePropertyChanged("INTL_TXN_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long INTL_PARENT_TXN_ID {
            get {
                return this.iNTL_PARENT_TXN_IDField;
            }
            set {
                this.iNTL_PARENT_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_PARENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_PARENT_TXN_IDSpecified {
            get {
                return this.iNTL_PARENT_TXN_IDFieldSpecified;
            }
            set {
                this.iNTL_PARENT_TXN_IDFieldSpecified = value;
                this.RaisePropertyChanged("INTL_PARENT_TXN_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ACTION_DATE {
            get {
                return this.aCTION_DATEField;
            }
            set {
                this.aCTION_DATEField = value;
                this.RaisePropertyChanged("ACTION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACTION_DATESpecified {
            get {
                return this.aCTION_DATEFieldSpecified;
            }
            set {
                this.aCTION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("ACTION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public CHANGE_INFOType CHANGE_INFO {
            get {
                return this.cHANGE_INFOField;
            }
            set {
                this.cHANGE_INFOField = value;
                this.RaisePropertyChanged("CHANGE_INFO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=6)]
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
                this.RaisePropertyChanged("REASON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string APPLICATION_NAME {
            get {
                return this.aPPLICATION_NAMEField;
            }
            set {
                this.aPPLICATION_NAMEField = value;
                this.RaisePropertyChanged("APPLICATION_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=8)]
        public string HOSTNAME {
            get {
                return this.hOSTNAMEField;
            }
            set {
                this.hOSTNAMEField = value;
                this.RaisePropertyChanged("HOSTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=9)]
        public string CHANNEL_NAME {
            get {
                return this.cHANNEL_NAMEField;
            }
            set {
                this.cHANNEL_NAMEField = value;
                this.RaisePropertyChanged("CHANNEL_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=10)]
        public string SIMULATION_FLAG {
            get {
                return this.sIMULATION_FLAGField;
            }
            set {
                this.sIMULATION_FLAGField = value;
                this.RaisePropertyChanged("SIMULATION_FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=11)]
        public string COMPRESSED {
            get {
                return this.cOMPRESSEDField;
            }
            set {
                this.cOMPRESSEDField = value;
                this.RaisePropertyChanged("COMPRESSED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATTRIBUTES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ATTRIBUTESTYPE[] ATTRIBUTES {
            get {
                return this.aTTRIBUTESField;
            }
            set {
                this.aTTRIBUTESField = value;
                this.RaisePropertyChanged("ATTRIBUTES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetGibUserListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAccountRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUserAuthorizationRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_HEADERType REQUEST_HEADER {
            get {
                return this.rEQUEST_HEADERField;
            }
            set {
                this.rEQUEST_HEADERField = value;
                this.RaisePropertyChanged("REQUEST_HEADER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutRequest : REQUEST {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListRequest : REQUEST {
        
        private string tYPEField;
        
        private string dOCUMENT_TYPEField;
        
        private System.DateTime rEGISTER_TIME_STARTField;
        
        private bool rEGISTER_TIME_STARTFieldSpecified;
        
        private ALIAS_TYPE aLIAS_TYPEField;
        
        private bool aLIAS_TYPEFieldSpecified;
        
        private System.DateTime aLIAS_MODIFY_DATEField;
        
        private bool aLIAS_MODIFY_DATEFieldSpecified;
        
        public GetGibUserListRequest() {
            this.tYPEField = "XML";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute("XML")]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
                this.RaisePropertyChanged("DOCUMENT_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime REGISTER_TIME_START {
            get {
                return this.rEGISTER_TIME_STARTField;
            }
            set {
                this.rEGISTER_TIME_STARTField = value;
                this.RaisePropertyChanged("REGISTER_TIME_START");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REGISTER_TIME_STARTSpecified {
            get {
                return this.rEGISTER_TIME_STARTFieldSpecified;
            }
            set {
                this.rEGISTER_TIME_STARTFieldSpecified = value;
                this.RaisePropertyChanged("REGISTER_TIME_STARTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ALIAS_TYPE ALIAS_TYPE {
            get {
                return this.aLIAS_TYPEField;
            }
            set {
                this.aLIAS_TYPEField = value;
                this.RaisePropertyChanged("ALIAS_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ALIAS_TYPESpecified {
            get {
                return this.aLIAS_TYPEFieldSpecified;
            }
            set {
                this.aLIAS_TYPEFieldSpecified = value;
                this.RaisePropertyChanged("ALIAS_TYPESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ALIAS_MODIFY_DATE {
            get {
                return this.aLIAS_MODIFY_DATEField;
            }
            set {
                this.aLIAS_MODIFY_DATEField = value;
                this.RaisePropertyChanged("ALIAS_MODIFY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ALIAS_MODIFY_DATESpecified {
            get {
                return this.aLIAS_MODIFY_DATEFieldSpecified;
            }
            set {
                this.aLIAS_MODIFY_DATEFieldSpecified = value;
                this.RaisePropertyChanged("ALIAS_MODIFY_DATESpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum ALIAS_TYPE {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        GB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetAccountRequest : REQUEST {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginRequest : REQUEST {
        
        private string uSER_NAMEField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string USER_NAME {
            get {
                return this.uSER_NAMEField;
            }
            set {
                this.uSER_NAMEField = value;
                this.RaisePropertyChanged("USER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
                this.RaisePropertyChanged("PASSWORD");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserRequest : REQUEST {
        
        private GIBUSER uSERField;
        
        private string dOCUMENT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GIBUSER USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
                this.RaisePropertyChanged("DOCUMENT_TYPE");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationRequest : REQUEST {
        
        private PRODUCT pRODUCTField;
        
        private PRODUCT_DETAIL_FLAG pRODUCT_DETAIL_FLAGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PRODUCT PRODUCT {
            get {
                return this.pRODUCTField;
            }
            set {
                this.pRODUCTField = value;
                this.RaisePropertyChanged("PRODUCT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PRODUCT_DETAIL_FLAG PRODUCT_DETAIL_FLAG {
            get {
                return this.pRODUCT_DETAIL_FLAGField;
            }
            set {
                this.pRODUCT_DETAIL_FLAGField = value;
                this.RaisePropertyChanged("PRODUCT_DETAIL_FLAG");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT {
        
        /// <remarks/>
        EINVOICE,
        
        /// <remarks/>
        EARCHIVE,
        
        /// <remarks/>
        EDESPATCH,
        
        /// <remarks/>
        CREDITNOTE,
        
        /// <remarks/>
        RECONCILIATION,
        
        /// <remarks/>
        CONNECTOR,
        
        /// <remarks/>
        ELEDGER,
        
        /// <remarks/>
        ELEDGERARCHIVE,
        
        /// <remarks/>
        EINVOICEARCHIVE,
        
        /// <remarks/>
        ESMM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT_DETAIL_FLAG {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", ConfigurationName="AuthenticationWS.AuthenticationServicePort")]
    public interface AuthenticationServicePort {
        
        // CODEGEN: Generating message contract since the operation Login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Izibiz.AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/Login/Fault/RequestFault" +
            "Message", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        Izibiz.AuthenticationWS.LoginResponse1 Login(Izibiz.AuthenticationWS.LoginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginResponse")]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.LoginResponse1> LoginAsync(Izibiz.AuthenticationWS.LoginRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CheckUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Izibiz.AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUser/Fault/RequestF" +
            "aultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        Izibiz.AuthenticationWS.CheckUserResponse1 CheckUser(Izibiz.AuthenticationWS.CheckUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserResponse")]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.CheckUserResponse1> CheckUserAsync(Izibiz.AuthenticationWS.CheckUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetUserAuthorization is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationRequ" +
            "est", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Izibiz.AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorization/Fau" +
            "lt/RequestFaultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        Izibiz.AuthenticationWS.GetUserAuthorizationResponse1 GetUserAuthorization(Izibiz.AuthenticationWS.GetUserAuthorizationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationRequ" +
            "est", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationResp" +
            "onse")]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetUserAuthorizationResponse1> GetUserAuthorizationAsync(Izibiz.AuthenticationWS.GetUserAuthorizationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetGibUserList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Izibiz.AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserList/Fault/Req" +
            "uestFaultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        Izibiz.AuthenticationWS.GetGibUserListResponse1 GetGibUserList(Izibiz.AuthenticationWS.GetGibUserListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListResponse")]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetGibUserListResponse1> GetGibUserListAsync(Izibiz.AuthenticationWS.GetGibUserListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Izibiz.AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccount/Fault/Request" +
            "FaultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        Izibiz.AuthenticationWS.GetAccountResponse1 GetAccount(Izibiz.AuthenticationWS.GetAccountRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountResponse")]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetAccountResponse1> GetAccountAsync(Izibiz.AuthenticationWS.GetAccountRequest1 request);
        
        // CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Izibiz.AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/Logout/Fault/RequestFaul" +
            "tMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        Izibiz.AuthenticationWS.LogoutResponse1 Logout(Izibiz.AuthenticationWS.LogoutRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutResponse")]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.LogoutResponse1> LogoutAsync(Izibiz.AuthenticationWS.LogoutRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.LoginRequest LoginRequest;
        
        public LoginRequest1() {
        }
        
        public LoginRequest1(Izibiz.AuthenticationWS.LoginRequest LoginRequest) {
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.LoginResponse LoginResponse;
        
        public LoginResponse1() {
        }
        
        public LoginResponse1(Izibiz.AuthenticationWS.LoginResponse LoginResponse) {
            this.LoginResponse = LoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private GIBUSER[] uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GIBUSER[] USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.CheckUserRequest CheckUserRequest;
        
        public CheckUserRequest1() {
        }
        
        public CheckUserRequest1(Izibiz.AuthenticationWS.CheckUserRequest CheckUserRequest) {
            this.CheckUserRequest = CheckUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.CheckUserResponse CheckUserResponse;
        
        public CheckUserResponse1() {
        }
        
        public CheckUserResponse1(Izibiz.AuthenticationWS.CheckUserResponse CheckUserResponse) {
            this.CheckUserResponse = CheckUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AUTHORIZED aUTHORIZEDField;
        
        private bool aUTHORIZEDFieldSpecified;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private PRODUCT[] pRODUCT_LISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AUTHORIZED AUTHORIZED {
            get {
                return this.aUTHORIZEDField;
            }
            set {
                this.aUTHORIZEDField = value;
                this.RaisePropertyChanged("AUTHORIZED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AUTHORIZEDSpecified {
            get {
                return this.aUTHORIZEDFieldSpecified;
            }
            set {
                this.aUTHORIZEDFieldSpecified = value;
                this.RaisePropertyChanged("AUTHORIZEDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PRODUCT[] PRODUCT_LIST {
            get {
                return this.pRODUCT_LISTField;
            }
            set {
                this.pRODUCT_LISTField = value;
                this.RaisePropertyChanged("PRODUCT_LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum AUTHORIZED {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthorizationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest;
        
        public GetUserAuthorizationRequest1() {
        }
        
        public GetUserAuthorizationRequest1(Izibiz.AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            this.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthorizationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.GetUserAuthorizationResponse GetUserAuthorizationResponse;
        
        public GetUserAuthorizationResponse1() {
        }
        
        public GetUserAuthorizationResponse1(Izibiz.AuthenticationWS.GetUserAuthorizationResponse GetUserAuthorizationResponse) {
            this.GetUserAuthorizationResponse = GetUserAuthorizationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private base64Binary cONTENTField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public base64Binary CONTENT {
            get {
                return this.cONTENTField;
            }
            set {
                this.cONTENTField = value;
                this.RaisePropertyChanged("CONTENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGibUserListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.GetGibUserListRequest GetGibUserListRequest;
        
        public GetGibUserListRequest1() {
        }
        
        public GetGibUserListRequest1(Izibiz.AuthenticationWS.GetGibUserListRequest GetGibUserListRequest) {
            this.GetGibUserListRequest = GetGibUserListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGibUserListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.GetGibUserListResponse GetGibUserListResponse;
        
        public GetGibUserListResponse1() {
        }
        
        public GetGibUserListResponse1(Izibiz.AuthenticationWS.GetGibUserListResponse GetGibUserListResponse) {
            this.GetGibUserListResponse = GetGibUserListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetAccountResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private ACCOUNT_ADDRESS aCCOUNT_ADDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ACCOUNT_ADDRESS ACCOUNT_ADDRESS {
            get {
                return this.aCCOUNT_ADDRESSField;
            }
            set {
                this.aCCOUNT_ADDRESSField = value;
                this.RaisePropertyChanged("ACCOUNT_ADDRESS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class ACCOUNT_ADDRESS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cOMMERCIAL_NAMEField;
        
        private string fIRST_NAMEField;
        
        private string lAST_NAMEField;
        
        private string vKN_TCKNOField;
        
        private string eMAILField;
        
        private string wEBSITEField;
        
        private string tAX_OFFICEField;
        
        private string sICIL_NOField;
        
        private string mERSIS_NOField;
        
        private string iSLETME_MERKEZIField;
        
        private string sTREETField;
        
        private string bUILDING_NAMEField;
        
        private string bUILDING_NOField;
        
        private string hOUSE_NOField;
        
        private string sUB_CITYField;
        
        private string dISTRICTField;
        
        private string cITYField;
        
        private string rEGIONField;
        
        private string cOUNTRYField;
        
        private string pOSTAL_CODEField;
        
        private string tELNOField;
        
        private string fAXNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string COMMERCIAL_NAME {
            get {
                return this.cOMMERCIAL_NAMEField;
            }
            set {
                this.cOMMERCIAL_NAMEField = value;
                this.RaisePropertyChanged("COMMERCIAL_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FIRST_NAME {
            get {
                return this.fIRST_NAMEField;
            }
            set {
                this.fIRST_NAMEField = value;
                this.RaisePropertyChanged("FIRST_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LAST_NAME {
            get {
                return this.lAST_NAMEField;
            }
            set {
                this.lAST_NAMEField = value;
                this.RaisePropertyChanged("LAST_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VKN_TCKNO {
            get {
                return this.vKN_TCKNOField;
            }
            set {
                this.vKN_TCKNOField = value;
                this.RaisePropertyChanged("VKN_TCKNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
                this.RaisePropertyChanged("EMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string WEBSITE {
            get {
                return this.wEBSITEField;
            }
            set {
                this.wEBSITEField = value;
                this.RaisePropertyChanged("WEBSITE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TAX_OFFICE {
            get {
                return this.tAX_OFFICEField;
            }
            set {
                this.tAX_OFFICEField = value;
                this.RaisePropertyChanged("TAX_OFFICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SICIL_NO {
            get {
                return this.sICIL_NOField;
            }
            set {
                this.sICIL_NOField = value;
                this.RaisePropertyChanged("SICIL_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MERSIS_NO {
            get {
                return this.mERSIS_NOField;
            }
            set {
                this.mERSIS_NOField = value;
                this.RaisePropertyChanged("MERSIS_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ISLETME_MERKEZI {
            get {
                return this.iSLETME_MERKEZIField;
            }
            set {
                this.iSLETME_MERKEZIField = value;
                this.RaisePropertyChanged("ISLETME_MERKEZI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string STREET {
            get {
                return this.sTREETField;
            }
            set {
                this.sTREETField = value;
                this.RaisePropertyChanged("STREET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BUILDING_NAME {
            get {
                return this.bUILDING_NAMEField;
            }
            set {
                this.bUILDING_NAMEField = value;
                this.RaisePropertyChanged("BUILDING_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string BUILDING_NO {
            get {
                return this.bUILDING_NOField;
            }
            set {
                this.bUILDING_NOField = value;
                this.RaisePropertyChanged("BUILDING_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string HOUSE_NO {
            get {
                return this.hOUSE_NOField;
            }
            set {
                this.hOUSE_NOField = value;
                this.RaisePropertyChanged("HOUSE_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SUB_CITY {
            get {
                return this.sUB_CITYField;
            }
            set {
                this.sUB_CITYField = value;
                this.RaisePropertyChanged("SUB_CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string DISTRICT {
            get {
                return this.dISTRICTField;
            }
            set {
                this.dISTRICTField = value;
                this.RaisePropertyChanged("DISTRICT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=16)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
                this.RaisePropertyChanged("REGION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
                this.RaisePropertyChanged("COUNTRY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string POSTAL_CODE {
            get {
                return this.pOSTAL_CODEField;
            }
            set {
                this.pOSTAL_CODEField = value;
                this.RaisePropertyChanged("POSTAL_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string TELNO {
            get {
                return this.tELNOField;
            }
            set {
                this.tELNOField = value;
                this.RaisePropertyChanged("TELNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string FAXNO {
            get {
                return this.fAXNOField;
            }
            set {
                this.fAXNOField = value;
                this.RaisePropertyChanged("FAXNO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.GetAccountRequest GetAccountRequest;
        
        public GetAccountRequest1() {
        }
        
        public GetAccountRequest1(Izibiz.AuthenticationWS.GetAccountRequest GetAccountRequest) {
            this.GetAccountRequest = GetAccountRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.GetAccountResponse GetAccountResponse;
        
        public GetAccountResponse1() {
        }
        
        public GetAccountResponse1(Izibiz.AuthenticationWS.GetAccountResponse GetAccountResponse) {
            this.GetAccountResponse = GetAccountResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_RETURNType REQUEST_RETURN {
            get {
                return this.rEQUEST_RETURNField;
            }
            set {
                this.rEQUEST_RETURNField = value;
                this.RaisePropertyChanged("REQUEST_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_RETURNType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int rETURN_CODEField;
        
        private string[] wARNINGSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
                this.RaisePropertyChanged("CLIENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int RETURN_CODE {
            get {
                return this.rETURN_CODEField;
            }
            set {
                this.rETURN_CODEField = value;
                this.RaisePropertyChanged("RETURN_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WARNINGS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] WARNINGS {
            get {
                return this.wARNINGSField;
            }
            set {
                this.wARNINGSField = value;
                this.RaisePropertyChanged("WARNINGS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.LogoutRequest LogoutRequest;
        
        public LogoutRequest1() {
        }
        
        public LogoutRequest1(Izibiz.AuthenticationWS.LogoutRequest LogoutRequest) {
            this.LogoutRequest = LogoutRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public Izibiz.AuthenticationWS.LogoutResponse LogoutResponse;
        
        public LogoutResponse1() {
        }
        
        public LogoutResponse1(Izibiz.AuthenticationWS.LogoutResponse LogoutResponse) {
            this.LogoutResponse = LogoutResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServicePortChannel : Izibiz.AuthenticationWS.AuthenticationServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServicePortClient : System.ServiceModel.ClientBase<Izibiz.AuthenticationWS.AuthenticationServicePort>, Izibiz.AuthenticationWS.AuthenticationServicePort {
        
        public AuthenticationServicePortClient() {
        }
        
        public AuthenticationServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Izibiz.AuthenticationWS.LoginResponse1 Izibiz.AuthenticationWS.AuthenticationServicePort.Login(Izibiz.AuthenticationWS.LoginRequest1 request) {
            return base.Channel.Login(request);
        }
        
        public Izibiz.AuthenticationWS.LoginResponse Login(Izibiz.AuthenticationWS.LoginRequest LoginRequest) {
            Izibiz.AuthenticationWS.LoginRequest1 inValue = new Izibiz.AuthenticationWS.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            Izibiz.AuthenticationWS.LoginResponse1 retVal = ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).Login(inValue);
            return retVal.LoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.LoginResponse1> Izibiz.AuthenticationWS.AuthenticationServicePort.LoginAsync(Izibiz.AuthenticationWS.LoginRequest1 request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Izibiz.AuthenticationWS.LoginResponse1> LoginAsync(Izibiz.AuthenticationWS.LoginRequest LoginRequest) {
            Izibiz.AuthenticationWS.LoginRequest1 inValue = new Izibiz.AuthenticationWS.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            return ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Izibiz.AuthenticationWS.CheckUserResponse1 Izibiz.AuthenticationWS.AuthenticationServicePort.CheckUser(Izibiz.AuthenticationWS.CheckUserRequest1 request) {
            return base.Channel.CheckUser(request);
        }
        
        public Izibiz.AuthenticationWS.CheckUserResponse CheckUser(Izibiz.AuthenticationWS.CheckUserRequest CheckUserRequest) {
            Izibiz.AuthenticationWS.CheckUserRequest1 inValue = new Izibiz.AuthenticationWS.CheckUserRequest1();
            inValue.CheckUserRequest = CheckUserRequest;
            Izibiz.AuthenticationWS.CheckUserResponse1 retVal = ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).CheckUser(inValue);
            return retVal.CheckUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.CheckUserResponse1> Izibiz.AuthenticationWS.AuthenticationServicePort.CheckUserAsync(Izibiz.AuthenticationWS.CheckUserRequest1 request) {
            return base.Channel.CheckUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Izibiz.AuthenticationWS.CheckUserResponse1> CheckUserAsync(Izibiz.AuthenticationWS.CheckUserRequest CheckUserRequest) {
            Izibiz.AuthenticationWS.CheckUserRequest1 inValue = new Izibiz.AuthenticationWS.CheckUserRequest1();
            inValue.CheckUserRequest = CheckUserRequest;
            return ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).CheckUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Izibiz.AuthenticationWS.GetUserAuthorizationResponse1 Izibiz.AuthenticationWS.AuthenticationServicePort.GetUserAuthorization(Izibiz.AuthenticationWS.GetUserAuthorizationRequest1 request) {
            return base.Channel.GetUserAuthorization(request);
        }
        
        public Izibiz.AuthenticationWS.GetUserAuthorizationResponse GetUserAuthorization(Izibiz.AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            Izibiz.AuthenticationWS.GetUserAuthorizationRequest1 inValue = new Izibiz.AuthenticationWS.GetUserAuthorizationRequest1();
            inValue.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
            Izibiz.AuthenticationWS.GetUserAuthorizationResponse1 retVal = ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).GetUserAuthorization(inValue);
            return retVal.GetUserAuthorizationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetUserAuthorizationResponse1> Izibiz.AuthenticationWS.AuthenticationServicePort.GetUserAuthorizationAsync(Izibiz.AuthenticationWS.GetUserAuthorizationRequest1 request) {
            return base.Channel.GetUserAuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetUserAuthorizationResponse1> GetUserAuthorizationAsync(Izibiz.AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            Izibiz.AuthenticationWS.GetUserAuthorizationRequest1 inValue = new Izibiz.AuthenticationWS.GetUserAuthorizationRequest1();
            inValue.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
            return ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).GetUserAuthorizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Izibiz.AuthenticationWS.GetGibUserListResponse1 Izibiz.AuthenticationWS.AuthenticationServicePort.GetGibUserList(Izibiz.AuthenticationWS.GetGibUserListRequest1 request) {
            return base.Channel.GetGibUserList(request);
        }
        
        public Izibiz.AuthenticationWS.GetGibUserListResponse GetGibUserList(Izibiz.AuthenticationWS.GetGibUserListRequest GetGibUserListRequest) {
            Izibiz.AuthenticationWS.GetGibUserListRequest1 inValue = new Izibiz.AuthenticationWS.GetGibUserListRequest1();
            inValue.GetGibUserListRequest = GetGibUserListRequest;
            Izibiz.AuthenticationWS.GetGibUserListResponse1 retVal = ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).GetGibUserList(inValue);
            return retVal.GetGibUserListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetGibUserListResponse1> Izibiz.AuthenticationWS.AuthenticationServicePort.GetGibUserListAsync(Izibiz.AuthenticationWS.GetGibUserListRequest1 request) {
            return base.Channel.GetGibUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetGibUserListResponse1> GetGibUserListAsync(Izibiz.AuthenticationWS.GetGibUserListRequest GetGibUserListRequest) {
            Izibiz.AuthenticationWS.GetGibUserListRequest1 inValue = new Izibiz.AuthenticationWS.GetGibUserListRequest1();
            inValue.GetGibUserListRequest = GetGibUserListRequest;
            return ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).GetGibUserListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Izibiz.AuthenticationWS.GetAccountResponse1 Izibiz.AuthenticationWS.AuthenticationServicePort.GetAccount(Izibiz.AuthenticationWS.GetAccountRequest1 request) {
            return base.Channel.GetAccount(request);
        }
        
        public Izibiz.AuthenticationWS.GetAccountResponse GetAccount(Izibiz.AuthenticationWS.GetAccountRequest GetAccountRequest) {
            Izibiz.AuthenticationWS.GetAccountRequest1 inValue = new Izibiz.AuthenticationWS.GetAccountRequest1();
            inValue.GetAccountRequest = GetAccountRequest;
            Izibiz.AuthenticationWS.GetAccountResponse1 retVal = ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).GetAccount(inValue);
            return retVal.GetAccountResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetAccountResponse1> Izibiz.AuthenticationWS.AuthenticationServicePort.GetAccountAsync(Izibiz.AuthenticationWS.GetAccountRequest1 request) {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Izibiz.AuthenticationWS.GetAccountResponse1> GetAccountAsync(Izibiz.AuthenticationWS.GetAccountRequest GetAccountRequest) {
            Izibiz.AuthenticationWS.GetAccountRequest1 inValue = new Izibiz.AuthenticationWS.GetAccountRequest1();
            inValue.GetAccountRequest = GetAccountRequest;
            return ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Izibiz.AuthenticationWS.LogoutResponse1 Izibiz.AuthenticationWS.AuthenticationServicePort.Logout(Izibiz.AuthenticationWS.LogoutRequest1 request) {
            return base.Channel.Logout(request);
        }
        
        public Izibiz.AuthenticationWS.LogoutResponse Logout(Izibiz.AuthenticationWS.LogoutRequest LogoutRequest) {
            Izibiz.AuthenticationWS.LogoutRequest1 inValue = new Izibiz.AuthenticationWS.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            Izibiz.AuthenticationWS.LogoutResponse1 retVal = ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).Logout(inValue);
            return retVal.LogoutResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Izibiz.AuthenticationWS.LogoutResponse1> Izibiz.AuthenticationWS.AuthenticationServicePort.LogoutAsync(Izibiz.AuthenticationWS.LogoutRequest1 request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Izibiz.AuthenticationWS.LogoutResponse1> LogoutAsync(Izibiz.AuthenticationWS.LogoutRequest LogoutRequest) {
            Izibiz.AuthenticationWS.LogoutRequest1 inValue = new Izibiz.AuthenticationWS.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            return ((Izibiz.AuthenticationWS.AuthenticationServicePort)(this)).LogoutAsync(inValue);
        }
    }
}
